### ISSUE TITLE
Puppetfile is out of date

### ISSUE THREAD

**Issue by geetotes** [revelrylabs/our-boxen#3]
Our puppetfile is out of date with the master [boxen Puppetfile](https://github.com/boxen/our-boxen/blob/master/Puppetfile)

Updating the version numbers to match the master Puppetfile seems to resolve the 

```bash
Error: Could not apply complete catalog: Found 1 dependency cycle:
```

error that happens when installing on newer versions of Mac OS X

**Comment by vaxinate** [comment]
did a full update from boxen/our-boxen. closing
